[project]
name = "shres-first-llm-finetuning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "colorama>=0.4.6",
    "docling>=2.41.0",
    "langflow>=1.5.0.post1",
    "litellm>=1.60.2",
]
